CUDA_VISIBLE_DEVICES="0" python run_classification.py \
    --model_name_or_path  models/chinese-roberta-wwm-ext-large \
    --train_file data/classification_zh_train.json \
    --validation_file data/classification_zh_dev.json \
    --shuffle_train_dataset \
    --metric_name "accuracy" \
    --do_train \
    --do_eval \
    --max_seq_length 512 \
    --per_device_train_batch_size 16 \
    --learning_rate 2e-5 \
    --num_train_epochs 3 \
    --output_dir models/text_classification_zh