CUDA_VISIBLE_DEVICES="3" python cate_predict/run_classification.py \
    --do_predict \
    --model_name_or_path output/text_classification_zh \
    --train_file data/classification/classification_zh_train.json \
    --validation_file data/classification/classification_zh_dev.json \
    --test_file data/zh/cate_input/match2.json \
    --max_seq_length 512 \
    --per_device_eval_batch_size 400 \
    --metric_for_best_model "accuracy" \
    --save_strategy epoch \
    --evaluation_strategy epoch \
    --learning_rate 2e-5 \
    --num_train_epochs 3 \
    --output_dir data/zh/cate_output/predict_results2